### ISSUE TITLE
you're mod is conflicting with Apotheosis 

### ISSUE THREAD

**Issue by Klouver-github** [alxpettit/XpIsNoObject#1]
as I have apotheosis and Xp is No Object together, it'll cause to crash the launcher and sent back to the menu

**Comment by crabdancing** [comment]
Uh, I'd need to see your traceback to be able to help much with that. I peeked at the source for Apotheosis, and it looks like they're already overriding the `40` constant `AnvilScreenMixin` and `AnvilMenuMixin` with `MAX_INT` -- which is basically all my mod does. Why do you need my mod alongside theirs?

**Comment by crabdancing** [comment]
If the functionality is redundant, I should probably just add Apotheosis to a list of 'known mod incompatibilities', or somesuch. 🤔 Let me know if there's any reason to use both together, tho!
